name: Generate Areas Of Interest

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup DuckDB
      uses: opt-nc/setup-duckdb-action@v1.2.10

    - name: Extract to FlatGeobuf
      run: duckdb < lib/main.sql

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: areas-of-interest
        path: output.fgb
